# Generated by Django 5.0.7 on 2024-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
