# Generated by Django 5.0.7 on 2024-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_movie_trailer_url_movie_trailer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_code',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_embed_code',
            field=models.TextField(blank=True, help_text='Embed code for the trailer video'),
        ),
    ]
