# Generated by Django 5.0.7 on 2024-07-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_movie_trailer_code_movie_trailer_embed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_embed_code',
        ),
    ]
